name: checks

on:
  workflow_call:

jobs:
  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build sdist
        run: |
          pip install poetry-dynamic-versioning
          pip install poetry
          poetry dynamic-versioning enable
          poetry build -f sdist

      - uses: actions/upload-artifact@v3
        with:
          path: dist/*.tar.gz
