name: checks

on:
  workflow_call:
    inputs:
      package-name:
        required: true
        type: string
      python-version:
        required: true
        type: string
      min-coverage:
        required: true
        type: number

jobs:
  setup:
    uses: ./.github/workflows/setup.yml
    with:
      python-version: ${{ inputs.python-version }}

  linters:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ inputs.python-version }}

      - name: Load virtual environment
        uses: actions/cache@v2
        with:
          path: .venv
          key: ${{ runner.os }}-venv-${{ inputs.python-version }}-${{ hashFiles('pyproject.toml', 'poetry.lock') }}

      - name: Run linters and checks
        run: |
          source .venv/bin/activate
          echo ${{ inputs.package-name }}
          isort ${{ inputs.package-name }}
          black ${{ inputs.package-name }}
          flake8 ${{ inputs.package-name }}
          mypy ${{ inputs.package-name }} --install-types --non-interactive --config-file pyproject.toml
        env:
          PIP_DISABLE_PIP_VERSION_CHECK: 1

      - name: Save linter reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: linter-reports
          path: report-${{ inputs.python-version }}.xml

  tests:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ inputs.python-version }}

      - name: Load virtual environment
        uses: actions/cache@v2
        with:
          path: .venv
          key: ${{ runner.os }}-venv-${{ inputs.python-version }}-${{ hashFiles('pyproject.toml', 'poetry.lock') }}

      - name: Run shuffled tests
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 60
          max_attempts: 3
          command: |
            source .venv/bin/activate
            pytest --random-order --junitxml=tests-${{ inputs.python-version }}.xml
        env:
          PIP_DISABLE_PIP_VERSION_CHECK: 1

      - name: Save test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: tests-${{ inputs.python-version }}.xml

  coverage:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ inputs.python-version }}

      - name: Load virtual environment
        uses: actions/cache@v2
        with:
          path: .venv
          key: ${{ runner.os }}-venv-${{ inputs.python-version }}-${{ hashFiles('pyproject.toml', 'poetry.lock') }}

      - name: Run coverage
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 60
          max_attempts: 3
          command: |
            source .venv/bin/activate
            coverage run -m pytest
            coverage report --fail-under=${{inputs.min-coverage}}
            coverage xml -o coverage-${{ inputs.python-version }}.xml
        env:
          PIP_DISABLE_PIP_VERSION_CHECK: 1

      - name: Save coverage reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: coverage-${{ inputs.python-version }}.xml

      - name: Upload coverage reports to Codecov
        if: ${{ github.ref == 'refs/heads/main' && github.repository == 'openweathermap/deker'}}
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
