name: build_docs

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string

jobs:
  build_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Load virtual environment
        uses: actions/cache@v2
        with:
          path: .venv
          key: ${{ runner.os }}-venv-${{ inputs.python-version }}-${{ hashFiles('pyproject.toml', 'poetry.lock') }}

      - name: Make docs
        run: |
          source .venv/bin/activate
          doc8 --config pyproject.toml docs/deker
          cd ./docs
          make html
          awk 'NR >= 35 && NR <= 40' _build/html/index.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: docs/_build/html
