name: tox

on:
  workflow_call:
    inputs:
      package-name:
        required: true
        type: string

jobs:
  py39:
    uses: ./.github/workflows/checks.yml
    with:
      python-version: "3.9"
      package-name: ${{ inputs.package-name }}

  py310:
    uses: ./.github/workflows/checks.yml
    with:
      python-version: "3.10"
      package-name: ${{ inputs.package-name }}

  py311:
    uses: ./.github/workflows/checks.yml
    with:
      python-version: "3.11"
      package-name: ${{ inputs.package-name }}
