name: tox

on:
  workflow_call:
    inputs:
      project-name:
        required: true
        type: string

jobs:
  py39:
    uses: ./.github/workflows/checks.yml
    with:
      python-version: "3.9"
      project-name: ${{ inputs.project-name }}


  py310:
    uses: ./.github/workflows/checks.yml
    with:
      python-version: "3.10"
      project-name: ${{ inputs.project-name }}

  py311:
    uses: ./.github/workflows/checks.yml
    with:
      python-version: "3.11"
      project-name: ${{ inputs.project-name }}
