name: tox

on:
  workflow_call:
    inputs:
      min-coverage:
        required: true
        type: number
      package-name:
        type: string
        required: true

jobs:
  py39:
    uses: ./.github/workflows/checks.yml
    with:
      python-version: "3.9"
      package-name: ${{ inputs.package-name }}
      min-coverage: ${{ inputs.min-coverage }}

  py310:
    uses: ./.github/workflows/checks.yml
    with:
      python-version: "3.10"
      package-name: ${{ inputs.package-name }}
      min-coverage: ${{ inputs.min-coverage }}

  py311:
    uses: ./.github/workflows/checks.yml
    with:
      python-version: "3.11"
      package-name: ${{ inputs.package-name }}
      min-coverage: ${{ inputs.min-coverage }}
