name: tox

on:
  workflow_call:

jobs:
  py39:
    uses: ./.github/workflows/checks.yml
    with:
      python-version: "3.9"

  py310:
    uses: ./.github/workflows/checks.yml
    with:
      python-version: "3.10"

  py311:
    uses: ./.github/workflows/checks.yml
    with:
      python-version: "3.11"
